interests = [
    "technology",
    "artificial intelligence",
    "machine learning",
    "data science",
    "skiing",
    "investing",
    "traveling",
    "photography",
    "music",
    "gaming",
    "cooking",
    "reading",
    "hiking",
    "yoga",
    "cycling",
    "gardening",
    "fashion",
    "movies",
    "theater",
    "dancing",
    "writing",
    "blogging",
    "podcasting",
    "volunteering",
    "environmentalism",
    "politics",
    "history",
    "philosophy",
    "psychology",
    "astronomy",
    "space exploration",
    "robotics",
    "blockchain",
    "cryptocurrency",
    "virtual reality",
    "video games",
    "comics",
    "anime",
    "sports",
    "fitness",
    "nutrition",
    "meditation",
    "mindfulness",
    "travel blogging",
    "culinary arts",
    "wine tasting",
    "crafting",
    "off-roading",
    "surfing",
    "diving",
    "fishing",
    "bird watching",
    "camping",
    "rock climbing",
    "motorcycling",
    "woodworking",
    "pottery",
    "knitting",
    "scrapbooking",
    "calligraphy",
    "magic",
    "juggling",
    "film making",
    "boating",
    "sailing",
    "kayaking",
    "canoeing",
    "archery",
    "fencing",
    "martial arts",
    "pilates",
    "crossfit",
    "triathlon",
    "marathon running",
    "swimming",
    "stocks",
    "real estate",
]