specialties = [
    "Administrative Law",
    "Admiralty and Maritime Law",
    "Antitrust Law",
    "Appellate Practice",
    "Bankruptcy Law",
    "Civil Rights Law",
    "Constitutional Law",
    "Consumer Law",
    "Criminal Defense Law",
    "Criminal Prosecution Law",
    "Data Privacy and Security Law",
    "Education Law",
    "Elder Law",
    "Election Law",
    "Energy Law",
    "Entertainment Law",
    "Environmental Law",
    "Family Law",
    "Finance and Securities Law",
    "Health Care Law",
    "Immigration Law",
    "Intellectual Property Law",
    "International Law",
    "Labor and Employment Law",
    "Real Estate Law",
    "Cannabis Law and Regulation",
    "Veterans' Benefits Law",
    "Space Law and Orbital Debris",
    "Fashion and Design Law",
    "Microfinance and Impact Investing Law",
    "Autonomous Vehicle Law",
    "Native American Law",
    "Tribal Law",
    "Agricultural Law and Food Safety",
    "Sports Agent and Contract Law",
    "Juvenile Delinquency Law",
    "Military Justice and Courts-Martial",
    "Disability Rights and Accessibility Law (ADA)",
    "E-commerce and Online Retail Law",
    "Customs and International Trade Law",
    "Public Utility Regulation",
    "Emergency Management and Disaster Law",
    "Animal Welfare and Rights Law",
    "Franchising Law",
    "Campaign Finance Law",
    "Reproductive Rights Law",
    "Forensic Evidence and Science Law",
    "Aviation and Aircraft Financing Law",
    "Whistleblower Protection and Qui Tam Litigation",
    "Zoning, Land Use, and Planning Law",
    "Nonprofit and Tax-Exempt Organization Law",
    "Public-Private Partnership (P3) Law",
    "Digital Assets and Cryptocurrency Law",
    "Mining Law",
    "Surety and Fidelity Law",
    "Insurance Coverage Disputes",
    "Pharmaceutical and Medical Device Regulation (FDA)",
    "Art Law and Cultural Heritage",
    "Geographic Information Systems (GIS) Law",
    "Torts Litigation (Personal Injury)",
    "Products Liability Law",
    "Debt Collection and Credit Reporting Law (FDCPA)",
    "Construction Defect Litigation",
    "Data Governance and Information Lifecycle Management",
    "Hospitality and Tourism Law",
    "Professional Malpractice Law (Non-Medical)",
    "Water Rights and Resource Management Law",
    "Civil Forfeiture Law",
    "Restructuring and Insolvency Law",
    "Consumer Product Safety Commission (CPSC) Compliance",
    "International Arbitration",
    "Export Controls and Sanctions (ITAR/EAR)",
    "Unmanned Aerial Systems (Drone) Law",
    "Infrastructure and Project Finance Law",
    "Veterinary Malpractice Law",
    "Trademark Counterfeiting Litigation",
    "Hospital Credentialing and Peer Review Law",
    "Ocean and Coastal Zone Management Law",
    "Design Patent Law",
    "Public Records and Open Meetings Law (Sunshine Law)",
    "Cable, Satellite, and Broadcasting Law",
    "Government Contracts and Procurement Fraud",
    "Surety Bonding and Construction Claims",
    "Railway and Surface Transportation Law",
    "Foreign Corrupt Practices Act (FCPA) Compliance",
    "Cyber Liability and Data Breach Litigation",
    "Executive Compensation and Employee Benefits (ERISA)",
    "Liquor Licensing and Alcoholic Beverage Control Law",
    "Condominium and Homeowners' Association (HOA) Law",
    "Commercial Subrogation",
    "Trade Secret Misappropriation",
    "Police Misconduct and Excessive Force Litigation",
    "Veterans Affairs Disability Appeals",
    "Digital Millennium Copyright Act (DMCA) Issues",
    "Securities Fraud Litigation",
    "Offshore Wind Energy Regulation",
    "Unfair Competition Law",
    "Injunctions and Temporary Restraining Orders Practice",
    "Assisted Living and Long-Term Care Facility Regulation",
    "Bank Secrecy Act (BSA) and Anti-Money Laundering (AML)",
    "Tax Controversy and Litigation"
]